service: my-crawler

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: my-service
  memorySize: 128

functions:
  crawler:
    handler: handler.crawler
    events:
      - schedule: rate(1 day)